### ISSUE TITLE
feign https service not working on port other than 8443 or 443

### ISSUE THREAD

**Issue by ymmihw** [ymmihw/spring-cloud-consul#2]
feign https service not working on port other than 8443 or 443

Spring Boot 2.0.5
Cloud Finchley.SR1

```
feign.FeignException: status 400 reading FeignHttpsClient#greeting(); content:
Bad Request
This combination of host and port requires TLS.

	at feign.FeignException.errorStatus(FeignException.java:62) ~[feign-core-9.5.1.jar:na]
	at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:91) ~[feign-core-9.5.1.jar:na]
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:138) ~[feign-core-9.5.1.jar:na]
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76) ~[feign-core-9.5.1.jar:na]
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103) ~[feign-core-9.5.1.jar:na]
	at com.sun.proxy.$Proxy125.greeting(Unknown Source) ~[na:na]
	at com.ymmihw.spring.cloud.consul.https.HttpsController.getGreeting(HttpsController.java:16) ~[classes/:na]
```

**Comment by ymmihw** [comment]
upgrate Cloud to Finchley.SR4 to solve the issue
